version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    image: your-dockerhub-username/nextjs-app:latest
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # เพิ่มตัวแปรสภาพแวดล้อมอื่นๆ ตามต้องการ
      # - DATABASE_URL=
      # - API_KEY=
    volumes:
      - ./logs:/app/logs
    # หากมีการใช้งานฐานข้อมูลหรือ service อื่นๆ สามารถเพิ่ม depends_on ได้
    # depends_on:
    #   - database
