name: Next.js CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

# เพิ่ม permissions ให้กับ workflow เพื่อให้สามารถสร้าง release ได้
permissions:
  contents: write
  pull-requests: read

jobs:
  # ทดสอบแอปพลิเคชัน
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint || echo "Linting failed but continuing..."

      - name: Run tests
        run: npm test || echo "Tests failed but continuing..."

  # สร้างและ release แอปพลิเคชัน
  build-and-release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # สร้าง tag และ release เฉพาะเมื่อเป็นการ push ไปยัง main
      - name: Generate Tag
        id: tag
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          MAJOR=$(echo $LAST_TAG | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo $LAST_TAG | cut -d. -f2)
          PATCH=$(echo $LAST_TAG | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$NEW_PATCH"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "Generated new tag: $NEW_TAG"

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          release_name: Release ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false

      # กำหนด Docker tag ตามประเภทของ event
      - name: Set Docker Tag
        id: docker_tag
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            if [ "${{ github.base_ref }}" == "main" ]; then
              echo "tag=pr-main-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            else
              echo "tag=pr-dev-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            fi
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=${{ steps.tag.outputs.new_tag || 'latest' }}" >> $GITHUB_OUTPUT
          else
            echo "tag=develop" >> $GITHUB_OUTPUT
          fi

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker image เฉพาะเมื่อเป็น main หรือ develop
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/prod.Dockerfile
          push: ${{ github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.base_ref == 'main') }}
          tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-app:${{ steps.docker_tag.outputs.tag }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/nextjs-app:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/nextjs-app:buildcache,mode=max

      # Push latest tag เฉพาะเมื่อเป็น main
      - name: Tag and push latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker buildx build --push \
            --tag ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest \
            --file ./docker/prod.Dockerfile .
